services:
  db:
    container_name: oracle
    image: gvenzl/oracle-xe
    environment:
      - ORACLE_PASSWORD=oui
      - APP_USER=hangarstation
      - APP_USER_PASSWORD=hangarstation
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  sonar:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - sonarqube_data:/opt/sonarqube/data



  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8060:8080"
    volumes:
      - jenkins_home:/var/jenkins_home



volumes:
  oracle_data:
  redis_data:
  sonarqube_data:
  jenkins_home:


